name = str(input("Enter your full name: "))
length = len(name)
print(f"Your name is {length} characters long")
result = name.find("o")
print(f"The first eccourance of the letter o in your name is in the {result} position")
name = name.capitalize()
print(f"your name looks better this way {name}")
name = name.upper()
print(f"if you were screaming your  name it would look like this {name}")
name = name.lower()
print(f"if you were sleepy it would look like this {name}")